live_config_reload = true

import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 12.0

[font.bold_italic]
family = "Ubuntu Mono"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono"
style = "Italic"

[font.normal]
family = "Ubuntu Mono"
style = "Bold"

[scrolling]
history = 10000

[window]
decorations = "none"
dynamic_title = true
title = "Alacritty"

[window.padding]
x = 20
y = 10
