#!/bin/bash

if pidof wofi; then
	killall wofi
	exit 0
fi

entries="Logout\nReboot\nShutdown"

selected=$(printf "$entries" | wofi --style ~/dotfiles/wofi/powermenu.css --conf ~/dotfiles/wofi/powermenu.conf --cache-file /dev/null > awk '{print tolower($2)}')

case $selected in
  logout)
    notify-send "Logout" ;;
  reboot)
    echo "reboot" ;;
  shutdown)
    echo "shutdown" ;;
esac
