#!/bin/bash
#    ___      ___
#   |"  \    /"  | ⊏
#    \   \  //   | ⊓
#    /\   \/.    | ⊐
#   |: \.        | ⊔
#   |.  \    /:  | ⊏
#   |___|\__/|___| ⊓
#

do_convert () {

	local filename tmp newWidth newHeight
	
	filename=$(basename -- "$1")
	tmp=$(mktemp)
	tmp2=$(mktemp)

	if [[ ! $(file -b "$filename" | cut -d' ' -f1 ) = "PNG" ]]; then
		newfile="${filename%.*}.png"
		magick "$filename" "$newfile"
		filename="$newfile"
	fi

	if [ "$(identify -ping -format '%w' "$filename")" -gt 2560 ]; then

		# image is more than 2560px wide, scale down
		magick "$filename" -resize 2560x25000\> "$tmp"

		if [ "$(identify -ping -format '%h' "$tmp")" -lt 1440 ]; then

			# image height is too small now, repeat process the other way around
			magick "$filename" -resize 25000x1440\> "$tmp"
		fi
	fi

	newWidth=$(identify -ping -format '%w' "$tmp")
	newHeight=$(identify -ping -format '%h' "$tmp")
	
	if [[ "$newWidth" -gt 2560 ]] || [[ "$newHeight" -gt 1440 ]]; then

		# crop if width or height is too large after resize operation
		cp "$tmp" "$tmp2"
		magick "$tmp2" -gravity center -crop 2560x1440+0+0 "$tmp"
	fi

	cp "$tmp" "$HOME/Pictures/wallpapers/$filename"
}

do_convert "$@"
