#!/bin/bash

function print_fetch_default {

	local mainConf=~/dotfiles/main.conf
	local arrHex i rgb s c r uptime ram

	read -ra arrHex <<< "$(grep '^cMainGradient' $mainConf | cut -d: -f2 | xargs)"

	for (( i=0; i<${#arrHex[@]}; i++ )); do
		rgb=$(hex2rgb "${arrHex[i]}" | sed -e 's/ /;/g')
		printf -v s "%s%sm" "\x1b[38;2;" "$rgb"
		c+=("$s")
	done

	r="\x1b[0m"

	p () {

		if [ $# -eq 0 ]; then
			printf "\n"
		else
			if ! [ -v "${c[0]}" ]; then
				e=${c[$1]}
			fi
			printf "$e%s$r\n" "$2"
		fi
	}
	
	uptime=$(uptime -p | sed 's/up //')
	ram=$(free -m | grep 'Mem' | xargs | cut -d ' ' -f 3 | rev | sed 's/.../&./g;s/\.$//' | rev)

	p

	if ! [[ $* == *-t* ]]; then
		p 0 "    ___      ___"
		p 0 "   |\"  \    /\"  | ⊏"
		p 1 "    \   \  //   | ⊓"
		p 2 "    /\   \/.    | ⊐"
		p 3 "   |: \.        | ⊔"
		p 4 "   |.  \    /:  | ⊏"
		p 5 "   |___|\__/|___| ⊓"
		p
	fi
	if ! [[ $* == *-l* ]]; then
		p 0 "   user         $USER"
		p 1 "   host         $HOSTNAME"
		p 2 "   terminal     $TERM"
		p 3 "   shell        $SHELL"
		p 4 "   uptime       $uptime"
		p 5 "   ram usage    ${ram}MiB"
		p
	fi

	p
}

print_fetch_default "$@"
