#!/bin/bash

toggle_gamemode () {

	mainConfigFile="$HOME/dotfiles/main.conf"
	toggleFile="$HOME/dotfiles/toggles.conf"
	gamemodeState=$(grep 'gamemode' "$toggleFile" | cut -d= -f2 | xargs)

	if [ "$gamemodeState" = false ]; then
		hyprctl keyword decoration:active_opacity 1
		hyprctl keyword decoration:inactive_opacity 1
		hyprctl keyword decoration:blur:enabled false
		sed -i "s/gamemode.*/gamemode = true/" "$toggleFile"
	else
		defActiveOpacity=$(grep 'defActiveOpacity' "$mainConfigFile" | cut -d':' -f2 | xargs)
		defInactiveOpacity=$(grep 'defInactiveOpacity' "$mainConfigFile" | cut -d':' -f2 | xargs)
		hyprctl keyword decoration:active_opacity "$defActiveOpacity"
		hyprctl keyword decoration:inactive_opacity "$defInactiveOpacity"
		hyprctl keyword decoration:blur:enabled true
		sed -i "s/gamemode.*/gamemode = false/" "$toggleFile"
	fi
}

toggle_gamemode
