#!/bin/bash

cp -r ~/.config/hypr ~/github/dotfiles/
cp -r ~/.config/waybar ~/github/dotfiles/
cp ~/.config/wofi/style.css ~/github/dotfiles/wofi/
cp ~/.config/dunst/dunstrc ~/github/dotfiles/
cp -r ~/.config/eww ~/github/dotfiles/

cp -r ~/scripts ~/github/
