#!/bin/bash

rsync -a --delete ~/.config/hypr/ ~/github/dotfiles/hypr
rsync -a --delete ~/.config/waybar/ ~/github/dotfiles/waybar
rsync -a --delete ~/.config/eww/ ~/github/dotfiles/eww
cp ~/.config/wofi/style.css ~/github/dotfiles/wofi/
cp ~/.config/dunst/dunstrc ~/github/dotfiles/

rsync -a --delete ~/scripts/ ~/github/scripts
