#!/bin/bash

gitDir=/home/coen/github
dotsDir=/home/coen/dotfiles
scriptDir=/home/coen/scripts

if ! rsync --exclude "private.json" -aLK --delete "$dotsDir" "$gitDir"; then echo "Failed to sync dotfiles!"; fi
if ! rsync -aLK --delete "$scriptDir" "$gitDir"; then echo "Failed to sync scripts!"; fi
