#!/bin/bash

if [ $# -eq 0 ]; then exit 1; fi

input=$(echo "$1" | awk '{print toupper($0)}')

if ! [[ "$input" =~ ^[0-9A-F]{6}$ ]] ; then
    echo "Not a valid hex color"
    exit 1
fi

printf "%d %d %d" 0x${input:0:2} 0x${input:2:2} 0x${input:4:2}
