#!/bin/bash
#    ___      ___
#   |"  \    /"  | ⊏
#    \   \  //   | ⊓
#    /\   \/.    | ⊐
#   |: \.        | ⊔
#   |.  \    /:  | ⊏
#   |___|\__/|___| ⊓
#

installed () {
	pac_log=/var/log/pacman.log
	tmp_log=$(mktemp)
	tmp2_log=$(mktemp)
	tmp3_log=$(mktemp)
	trap 'rm -f $tmp_log' EXIT
	trap 'rm -f $tmp2_log' EXIT
	trap 'rm -f $tmp3_log' EXIT

	pacman -Qent | awk '{ print $1, "P"}' > "$tmp_log"
	pacman -Qm | awk '{ print $1, "Y" }' >> "$tmp_log"

	tac $pac_log | awk '/installed/ { print $4, $1 }' \
		| sed 's/T/ /g' \
		| sed 's/\+[0-9]*//g' \
		| sed 's/\[//g' \
		| sed 's/\]//g' > "$tmp2_log"

	printf "" > "$tmp3_log"

	printf "\e[4m%-17s %-21s\e[0m\n\n" "Install date" "Package"
	while read -r line; do

		logline=$(awk '{ print $2 }' <<< "$line")
		if [ "$logline" = "P" ]; then
			printf -v logline "\x1b[38;2;120;120;180m%s\x1b[0m " "$logline"
		else
			printf -v logline "\x1b[38;2;240;160;120m%s\x1b[0m " "$logline"
		fi
		line=$(awk '{ print $1 }' <<< "$line")
		logline+=$(grep "$line" "$tmp2_log" | head -1 | awk '{ print $2, $1 }')

		awk '{ printf "%s    %s   %s\n", $2, $1, $3 }' <<< "$logline"
		

	done < "$tmp_log"
	exit 0

}

paclog () {

	local curdate prevdate output line icon action colInstall colRemove rcol pacmanLog tmpLog newLog

	pacmanLog=/var/log/pacman.log
	tmpLog=/tmp/paclog.tmp
	newLog=/var/log/pacman_new.log
	icon=""

	qInstalled='/pacman -S [a-zA-Z0-9].*/'
	qUninstalled='/pacman -Rs [a-zA-Z0-9]/'

	printf "" > $tmpLog

	if [[ "$*" == *"w"* ]]; then
		local w=1
		printf "" > $newLog
	fi

	if [[ "$*" == *"i"* ]]; then
		awkQuery="$qInstalled"
	elif [[ "$*" == *"u"* ]]; then
		awkQuery="$qUninstalled"
	else
		awkQuery="${qInstalled}||${qUninstalled}"
	fi

	awk "${awkQuery}" $pacmanLog | \
	sed -e 's/\[//g' \
		-e 's/\]//g' \
		-e 's/T/ /g'\
		-e 's/'\''//g' \
		-e 's/+[0-9]*/ /g' \
		-e 's/[ ]{1,}/ /g' | \
	awk -v OFS=' ' '{print $1, $2, $6, $7}' > $tmpLog

	if [[ "$*" == *"r"* ]]; then

		local revtmp tmpLog2 arrDates

		revtmp=/tmp/paclog_rev.tmp
		tmpLog2=/tmp/paclog_rev2.tmp
		tac $tmpLog > $revtmp
		cat $tmpLog > $tmpLog2
		
		printf "" > $tmpLog

		read -ra arrDates <<< "$(cat $revtmp | awk '{print $1}' | uniq | xargs)"

		for ((i=0;i<${#arrDates[@]};i++)); do
			grep "${arrDates[i]}" $tmpLog2 >> $tmpLog
		done

		rm $revtmp
		rm $tmpLog2
	fi

	if [ -z "$w" ]; then
		colInstall=$(tput sgr0)
		colRemove=$(tput setaf 241)
		rcol=$(tput sgr0)
	fi

	IFS=''
	while read -r line; do

		line=$(xargs <<< "$line")

		curdate=$(awk '{print $1}' <<< "$line")
		curtime=$(awk '{print $2}' <<< "$line")
		action=$(awk '{print $3}' <<< "$line" | cut -c2)
		name=$(awk '{print $4}' <<< "$line")

		if [ -n "$w" ]; then
			if [ "$action" = "S" ]; then
				icon="+"
			else
				icon="-"
			fi
		fi

		output=""

		if [ -z "$prevdate" ]; then
			output+=$(printf "\n ╔════════════╕\n ║ %s │\n ╚═══════════════════════════════════════════════════════════════╗" "${curdate}")
			prevdate="$curdate"
		elif [ ! "$prevdate" = "$curdate" ]; then
			output+=$(printf "\n  ╘══════════════════════════════════════════════════════════════╝")
			output+=$(printf "\n\n ╔════════════╕\n ║ %s │\n ╚═══════════════════════════════════════════════════════════════╗" "${curdate}")
			prevdate=$curdate

		fi

		output+=$(printf "\n  │ ")

		if [ "$action" = "R" ]; then
			output+=$(printf "%s" "${colRemove}")
		else
			output+=$(printf "%s" "${colInstall}")
		fi

		output+=$(printf "%s " "${curtime}")

		output+=$(printf "%s %-48s" "$icon" "$name")
			
		output+=$(printf "%s" "${rcol}")

		output+=$(printf "  ║")

		if [ -n "$w" ]; then
			printf "%s" "$output" >> $newLog
		else
			printf "%s" "$output"
		fi

	done < $tmpLog

	if [ -n "$w" ]; then
		printf "\n  ╘══════════════════════════════════════════════════════════════╝\n\n" >> $newLog
		printf "\nLog written to %s\n\n" "$newLog"
	else
		printf "\n  ╘══════════════════════════════════════════════════════════════╝\n\n"
	fi	
}

main () {

	case "$@" in
		"-i"|"--installed") installed ;;
		"-r"|"--removed") removed ;;
		""|*) paclog "$2" ;;
	esac
}

main "$@"