#!/bin/bash

calc_percentage () {
	local used total
	used="$1"
	total="$2"
	echo "$used/$total*100" | bc -l | cut -d. -f1
}

stat_mem () {

	local used total perc percGraph graph usedPretty totalPretty rest fullStr

	while true; do

		used=$(free -m | grep 'Mem' | xargs | cut -d ' ' -f 3)
		total=$(free -m | grep 'Mem' | xargs | cut -d ' ' -f 2)

		usedPretty="$(echo "$used" | rev | sed 's/.../&./g;s/\.$//' | rev)"
		totalPretty="$(echo "$total" | rev | sed 's/.../&./g;s/\.$//' | rev)"

		perc=$(calc_percentage "$used" "$total")
		((percGraph=(perc+2)/5))

		graph="["
		for ((i=1;i<=percGraph;i++)); do
			graph+="● "
		done
		((rest=20-percGraph))
		for ((i=1;i<=rest;i++)); do
			graph+="○ "
		done
		graph+="]"

		fullStr="RAM: ${usedPretty}M \/ ${totalPretty}M"
		strLen=${#fullStr}
		for ((i=strLen;i<=26;i++)); do
			fullStr+=" "
		done

		sed -i "s/^RAM.*/${fullStr} ${graph}/" "$HOME/scripts/.stats.inf"

		sleep 1
	done
}

stat_ssd () {

	local used total graph usedPretty totalPretty percGraph perc rest fullStr

	while true; do
	
		used=$(du --exclude=/mnt -cs --block-size=M / 2>/dev/null | tail -1 | cut -d'M' -f1)
		total=$(df -H --block-size=M | grep "sdb3" | awk '{print $2}' | cut -d'M' -f1)

		usedPretty="$(echo "$used" | rev | sed 's/.../&./g;s/\.$//' | rev)"
		totalPretty="$(echo "$total" | rev | sed 's/.../&./g;s/\.$//' | rev)"
	
		perc=$(calc_percentage "$used" "$total")
		((percGraph=(perc+2)/5))
	
		graph="["
		for ((i=1;i<=percGraph;i++)); do
			graph+="● "
		done
		((rest=20-percGraph))
		for ((i=1;i<=rest;i++)); do
			graph+="○ "
		done
		graph+="]"
			
		fullStr="SSD: ${usedPretty}M \/ ${totalPretty}M"
		strLen=${#fullStr}

		for ((i=strLen;i<=26;i++)); do
			fullStr+=" "
		done
		
		sed -i "s/SSD.*/${fullStr} ${graph}/" "$HOME/scripts/.stats.inf"
		
		sleep 15
	done
}

stat_watch () {

	stat_mem &
	stat_ssd &	
	alacritty --config-file "$HOME/dotfiles/alacritty/floater.yml" -e bash -c 'tput civis && watch -t -n1 cat $HOME/scripts/.stats.inf'
}

main () {
	case "$1" in

		"-ram") stat_mem ;;
		"-ssd") stat_ssd ;;
		"-w") stat_watch ;;
		"--run") start ;;
	esac
}

main "$@"
