#!/bin/bash

read -r -a arrHex <<< "$(grep '^cMainGradient' ~/dotfiles/main.conf | cut -d: -f2)" &>/dev/null

echo "" > ~/dotfiles/waybar/colors.css

for (( i=0; i<${#arrHex[@]}; i++ )); do
	printf "@define-color grad$i #%s;\n" "${arrHex[$i]}" >> ~/dotfiles/waybar/colors.css
done

defTxt=$(grep 'cMainText' ~/dotfiles/main.conf | cut -d: -f2 | xargs)
printf "@define-color defText #%s;" "$defTxt" >> ~/dotfiles/waybar/colors.css
