#!/bin/bash
#    ___      ___
#   |"  \    /"  | ⊏
#    \   \  //   | ⊓
#    /\   \/.    | ⊐
#   |: \.        | ⊔
#   |.  \    /:  | ⊏
#   |___|\__/|___| ⊓
#

do_convert () {
	local filename tmp new_width new_height
	
	filename=$(basename -- "$1")
	tmp=$(mktemp)

	if [[ $(file -b "$filename" | cut -d' ' -f1 ) != "PNG" ]]; then
		newfile="${filename%.*}.png"
		magick "$filename" "$newfile"
		filename="$newfile"
	fi

	if [ "$(identify -ping -format '%w' "$filename")" -gt 2560 ]; then

		# image is more than 2560px wide, scale down
		magick "$filename" -resize 2560x25000\> "$tmp"

		if [ "$(identify -ping -format '%h' "$tmp")" -lt 1440 ]; then

			# image height is too small now, repeat process the other way around
			magick "$filename" -resize 25000x1440\> "$tmp"
		fi
	fi

	new_width=$(identify -ping -format '%w' "$tmp")
	new_height=$(identify -ping -format '%h' "$tmp")
	
	if (( new_width > 2560 || new_height > 1440 )); then

		magick "$tmp" -gravity center -crop 2560x1440+0+0 "$tmp"
	fi

	cp "$tmp" "$HOME/Pictures/wallpapers/$filename"
	rm -f "$tmp"
}

do_convert "$@"
