#!/bin/bash

configFile=~/dotfiles/main.conf
configMd5=~/dotfiles/.config-md5

check_change () {
	if [ "$(md5sum $configFile | cut -d' ' -f1)" = "$(cat $configMd5)" ]; then
		exit 0
	else
		update_styles
		md5sum "$configFile" | cut -d' ' -f1 > "$configMd5"
	fi
}

update_styles () {

	# update waybar styles

	local waybarColorsFile arrWaybarGradient waybarText

	waybarColorsFile=~/dotfiles/waybar/colors.css
	
	read -r -a arrWaybarGradient <<< "$(get-colors -c cMainWaybarGradient)"

	printf "" > "$waybarColorsFile"
	for (( i=0; i<${#arrWaybarGradient[@]}; i++ )); do
		printf "@define-color grad$i #%s;\n" "${arrWaybarGradient[i]}" >> "$waybarColorsFile"
	done

	waybarText="$(get-colors -c cMainWaybarText)"
	printf "@define-color defText #%s;" "$waybarText" >> "$waybarColorsFile"
}

check_change "$@"
