#!/bin/bash

function module_clock {
	date '+%H:%M %Y-%m-%d'
}

function module_ram {
	free | awk '/^Mem/ { printf("%02d%%", $3/$2 * 100.0) }'
}

function module_cpu {
	printf "%02d%%" "$(mpstat --dec=0 | tail -1 | awk '{print $NF}' | awk '{print 100-$1}')"
}

function module_weather {
	local meteo temperature precipitation cloud_cover icon

	meteo=$(curl -s "https://api.open-meteo.com/v1/forecast?latitude=51.6992&longitude=5.3042&current=temperature_2m,cloud_cover,precipitation&timezone=auto" | jq '.current' | grep -E 'temperature|precipitation|cloud_cover' | sed 's/,//g')

	temperature=$(grep 'temperature_2m' <<< "$meteo" | awk '{print $2}')
	precipitation=$(grep 'precipitation' <<< "$meteo" | awk '{print $2}')
	cloud_cover=$(grep 'cloud_cover' <<< "$meteo" | awk '{print $2}')

	if (( $(echo "$precipitation > 1" | bc -l) )); then
		icon="rain"
	elif (( $(echo "$cloud_cover > 80" | bc -l) )); then
		icon="clouds"
	else
		icon="clear"
	fi

	printf "{ \"text\": \"%s°C\", \"alt\": \"%s\" }\n" "$temperature" "$icon"

}

function module_toggles {
	local arrToggleFiles arrToggleIcons toggles

	arrToggleFiles=(
		"/tmp/gamemode.toggle"
		"/tmp/gammastep.toggle"
	)
	
	arrToggleIcons=(
		""
		""
	)

	toggles=""
	for ((i=0; i<${#arrToggleFiles[@]}; i++)); do
		[[ -f ${arrToggleFiles[i]} ]] && toggles+="  ${arrToggleIcons[i]}  "
	done

	printf "%s" "$toggles"
}

function main {
	case "$1" in
		"--clock") module_clock ;;
		"--ram") module_ram ;;
		"--cpu") module_cpu ;;
		"--weather") module_weather ;;
		"--toggles") module_toggles ;;
	esac
}

main "$@"