#!/bin/bash


volume=$(amixer -D pulse sget Master | tail -1 | cut -d '[' -f 2 | cut -d ']' -f 1)

if amixer -D pulse sget Master | tail -1 | grep "off" &>/dev/null; then

	volume="00%"

fi

printf "%s" "$volume"
