#!/bin/bash

update_workspaces () {
	# wsList=("$(hyprctl workspaces -j | grep 'id' | cut -c11 | xargs)")
	wsActive=$(hyprctl activeworkspace | head -1 | cut -d ' ' -f 3)
	wsListRaw=("$(hyprctl workspaces -j | grep 'id.: [0-9],$' | cut -c11 | xargs)")
	IFS=$' ' wsList=($(sort <<<"${wsListRaw[*]}"))

	wsModule="(box :class \"workspaces\" "

	for i in ${wsList[@]}; do
		if [ ! "$wsActive" -eq "$i" ]; then
			wsModule+="(button :onclick \"hyprctl dispatch workspace ${i}\" ${i})"
		else
			wsModule+="(button :class \"active-workspace\" :onclick \"hyprctl dispatch workspace ${i}\" ${i})"
		fi
	done
	wsModule+=")"
	echo "$wsModule"
}

update_workspaces # run the update once so that workspaces show up on start

handle () {
	 case $1 in
	 	workspace*) update_workspaces ;;
	 	focusedmon*) update_workspaces ;;
	 esac
}

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do 
	handle $line
done
