#!/bin/bash

toggle_gaps () {
	currentGap=$(grep 'margin-top' < ~/dotfiles/waybar/config | xargs | cut -d ' ' -f 2 | cut -d ',' -f 1)
	if [ "$currentGap" = "8" ]; then
		sed -i 's/width": 2544/width": 2560/' ~/dotfiles/waybar/config
		sed -i 's/margin-top": 8/margin-top": 0/' ~/dotfiles/waybar/config
		sed -i 's/spacing": 4/spacing": 0/' ~/dotfiles/waybar/config
		hyprctl keyword general:gaps_out 0
		hyprctl keyword general:gaps_in 0
	else
		sed -i 's/width": 2560/width": 2544/' ~/dotfiles/waybar/config
		sed -i 's/margin-top": 0/margin-top": 8/' ~/dotfiles/waybar/config
		sed -i 's/spacing": 0/spacing": 4/' ~/dotfiles/waybar/config
		hyprctl keyword general:gaps_out 8px
		hyprctl keyword general:gaps_in 4px
	fi

	killall waybar &>/dev/null
	nohup waybar </dev/null >/dev/null 2>&1 &
}

toggle_gaps
