#!/bin/bash

toggle_gaps () {

	defGapIn=3
	defGapOut=$((defGapIn*2))
	defBorderRadius=5

	currGap=$(hyprctl getoption general:gaps_out | grep "int" | cut -d' ' -f2)

	if [[ $currGap -eq 0 ]]; then
		newGapOut=$defGapOut
		newGapIn=$((defGapOut/2))
		newBarGap=0
		newBorderRadius=$defBorderRadius
	else
		newGapOut=0
		newGapIn=0
		newBarGap=$currGap
		newBorderRadius=0
	fi

	hyprctl keyword general:gaps_in $newGapIn &>/dev/null
	hyprctl keyword general:gaps_out $newGapOut &>/dev/null
	hyprctl keyword decoration:rounding $newBorderRadius &>/dev/null

	sed -i "s#[0-9], //gap#$newBarGap, //gap#" ~/dotfiles/waybar/config
	killall waybar &>/dev/null
	nohup waybar </dev/null >/dev/null 2>&1 &
}

toggle_gaps
